/**
 * data.ts — Translations (AR / FR / EN) + demo data for Zed Earn
 */

export type Lang = 'ar' | 'fr' | 'en';

export const LANGS: { code: Lang; label: string; flag: string }[] = [
  { code: 'ar', label: 'العربية', flag: '🇩🇿' },
  { code: 'fr', label: 'Français', flag: '🇫🇷' },
  { code: 'en', label: 'English', flag: '🇬🇧' },
];

type Dict = Record<string, string>;

const ar: Dict = {
  appName: 'Zed Earn',
  tagline: 'اربح بالدينار الجزائري من هاتفك',
  loading: 'جاري التحميل',

  next: 'التالي',
  startNow: 'ابدأ الآن',
  skip: 'تخطي',
  save: 'حفظ',
  cancel: 'إلغاء',
  back: 'رجوع',
  send: 'إرسال',
  copy: 'نسخ',
  share: 'مشاركة',
  close: 'إغلاق',
  confirm: 'تأكيد',
  seeAll: 'عرض الكل',
  dzd: 'دج',
  optional: 'اختياري',

  onb1Title: 'اعمل من هاتفك',
  onb1Desc: 'أنجز مهام تسويقية بسيطة في أي وقت ومن أي مكان في الجزائر، كل ما تحتاجه هو هاتفك واتصال بالإنترنت.',
  onb2Title: 'عمولات بالدينار الجزائري',
  onb2Desc: 'احصل على عمولاتك بالدينار الجزائري (DZD) واسحبها عبر CCP بريد الجزائر أو المحافظ الإلكترونية.',
  onb3Title: 'ابدأ رحلتك الآن',
  onb3Desc: 'سجّل حسابك في أقل من دقيقة، أكمل ملفك الشخصي وابدأ في تنفيذ أول مهمة مدفوعة اليوم.',

  login: 'تسجيل الدخول',
  signup: 'إنشاء حساب',
  authSubLogin: 'مرحباً بعودتك! أدخل رقم هاتفك للمتابعة',
  authSubSignup: 'أنشئ حسابك مجاناً وابدأ الربح اليوم',
  phone: 'رقم الهاتف',
  phoneHint: 'يجب أن يبدأ بـ 05 أو 06 أو 07',
  email: 'البريد الإلكتروني',
  emailOpt: 'البريد الإلكتروني (اختياري)',
  agreeTerms: 'أوافق على الشروط والأحكام وسياسة الخصوصية',
  haveAccount: 'لديك حساب؟ سجّل الدخول',
  noAccount: 'ليس لديك حساب؟ أنشئ واحداً',
  invalidPhone: 'رقم هاتف جزائري غير صالح',
  mustAgree: 'يجب الموافقة على الشروط أولاً',

  otpTitle: 'تأكيد رقم الهاتف',
  otpSubtitle: 'أدخل الرمز المكوّن من 6 أرقام المرسل إلى',
  otpDemo: 'رمز تجريبي',
  otpVerify: 'تأكيد',
  otpResend: 'إعادة إرسال الرمز',
  otpResent: 'تم إرسال رمز جديد',
  otpInvalid: 'الرمز غير صحيح، حاول مرة أخرى',

  guideTitle: 'دليل المستخدم',
  gIntro: 'المقدمة',
  gTasks: 'المهام',
  gComm: 'العمولات',
  gWd: 'السحب',
  gRules: 'القواعد',
  guideRead: 'لقد قرأت وفهمت',

  profileSetup: 'إكمال الملف الشخصي',
  profileSetupSub: 'ساعدنا في معرفتك أكثر لتسريع عمليات السحب',
  uploadAvatar: 'رفع صورة',
  fullName: 'الاسم الكامل',
  birthdate: 'تاريخ الميلاد',
  wilaya: 'الولاية',
  ccp: 'رقم CCP',
  ccpHint: 'يستعمل لعمليات السحب لاحقاً',
  profileSaved: 'تم حفظ ملفك الشخصي',

  home: 'الرئيسية',
  tasks: 'المهام',
  withdrawals: 'السحب',
  account: 'الحساب',
  hello: 'مرحباً',
  availableBalance: 'الرصيد المتاح',
  withdraw: 'سحب',
  deposit: 'إيداع',
  statTasks: 'مهام',
  statDone: 'مكتملة',
  statEarn: 'عمولات',
  availableTasks: 'مهام متاحة',
  noTasks: 'لا توجد مهام متاحة حالياً',

  easy: 'سهل',
  medium: 'متوسط',
  hard: 'صعب',
  vip: 'VIP',
  acceptTask: 'قبول المهمة',
  locked: 'مغلق',
  vipLockedMsg: 'أكمل 10 مهام لفتح مهام VIP',
  requirements: 'المتطلبات',
  steps: 'خطوات التنفيذ',
  uploadProof: 'رفع الإثبات',
  proofHint: 'أرفق لقطة شاشة أو صورة تثبت إنجاز المهمة',
  sendProof: 'إرسال الإثبات',
  cancelTask: 'إلغاء المهمة',
  taskAccepted: 'تم قبول المهمة، بالتوفيق!',
  taskCancelled: 'تم إلغاء المهمة',
  proofSent: 'تم إرسال الإثبات للمراجعة',
  reviewMsg: 'سنراجع الإثبات خلال 24 ساعة وسيتم إضافة العمولة تلقائياً.',
  doneMsg: 'تمت المهمة! تم إضافة {amount} إلى رصيدك',
  needProof: 'يرجى إرفاق إثبات أولاً',
  statusAvailable: 'متاحة',
  statusAccepted: 'مقبولة',
  statusReview: 'قيد المراجعة',
  statusDone: 'مكتملة',
  reward: 'العمولة',

  withdrawable: 'الرصيد القابل للسحب',
  minWithdraw: 'الحد الأدنى للسحب: 1,000 دج',
  wdMethods: 'طرق السحب',
  mCcp: 'CCP - بريد الجزائر',
  mCcpDesc: 'تحويل خلال 24 ساعة',
  mWallet: 'محافظ إلكترونية',
  mWalletDesc: 'D17 · Mobimoney · BaridiMob',
  mCard: 'بطاقة بنكية',
  mCardDesc: 'Visa / Mastercard · 3 أيام',
  wdHistory: 'سجل السحب',
  wdEmpty: 'لا توجد عمليات سحب بعد',
  amount: 'المبلغ',
  requestWithdraw: 'طلب السحب',
  belowMin: 'المبلغ أقل من الحد الأدنى (1,000 دج)',
  insufficient: 'رصيدك غير كافٍ',
  wdRequested: 'تم إرسال طلب السحب بنجاح',
  kycRequired: 'يجب توثيق هويتك (KYC) قبل السحب',
  depositTitle: 'إيداع رصيد',
  depositDone: 'تم إضافة الرصيد التجريبي',

  profile: 'الملف الشخصي',
  level: 'المستوى',
  lvlBeginner: 'مبتدئ',
  lvlActive: 'نشط',
  lvlPro: 'محترف',
  lvlVip: 'VIP',
  nextLevel: 'التقدم نحو {level}',
  maxLevel: 'وصلت لأعلى مستوى 🎉',
  settings: 'الإعدادات',
  kyc: 'التحقق من الهوية (KYC)',
  referral: 'الإحالات',
  leaderboard: 'المتصدرين',
  wallet: 'المحفظة والمعاملات',
  support: 'الدعم الفني',
  merchant: 'وضع التاجر',
  logout: 'تسجيل الخروج',
  loggedOut: 'تم تسجيل الخروج',
  darkMode: 'الوضع الليلي',
  language: 'اللغة',
  verified: 'موثّق',
  unverified: 'غير موثّق',

  kycTitle: 'التحقق من الهوية',
  kycNone: 'غير مكتمل',
  kycReview: 'قيد المراجعة',
  kycVerified: 'تم التحقق',
  kycNote: 'صورك محمية ولا تُستعمل إلا للتحقق من هويتك.',
  idFront: 'بطاقة التعريف (الوجه)',
  idBack: 'بطاقة التعريف (الظهر)',
  selfie: 'سيلفي مع البطاقة',
  kycSubmit: 'إرسال للتحقق',
  kycMissing: 'يرجى رفع الصور الثلاث',
  kycSent: 'تم إرسال مستنداتك للمراجعة',
  tapToUpload: 'اضغط للرفع',

  refTitle: 'الإحالات',
  yourCode: 'كود الإحالة الخاص بك',
  refDesc: 'شارك كودك واربح 500 دج عن كل صديق ينضم ويكمل أول مهمة.',
  copied: 'تم نسخ الكود',
  refCount: 'إحالاتي',
  refEarn: 'أرباح الإحالات',
  refTotal: 'الإجمالي',
  shareMsg: 'انضم إلى Zed Earn واربح بالدينار الجزائري! استعمل كودي: {code}',

  lbTitle: 'المتصدرين',
  lbSub: 'أفضل 10 مسوقين هذا الشهر',
  tasksCount: 'مهمة',

  notifications: 'الإشعارات',
  notifEmpty: 'لا توجد إشعارات',
  markAllRead: 'تحديد الكل كمقروء',
  markRead: 'تحديد كمقروء',
  allRead: 'تم تحديد كل الإشعارات كمقروءة',

  chatTitle: 'الدعم الفني',
  chatPlaceholder: 'اكتب رسالتك...',
  supportName: 'فريق Zed Earn',
  chatAuto: 'شكراً على تواصلك! فريقنا يراجع رسالتك وسيرد عليك خلال دقائق. هل يمكنك توضيح المشكلة أكثر؟',

  merchantTitle: 'وضع التاجر',
  mProducts: 'منتجاتي',
  mActive: 'مهام نشطة',
  mSales: 'مبيعات',
  mRevenue: 'إيرادات',
  addProduct: 'إضافة منتج جديد',
  productName: 'اسم المنتج',
  productPrice: 'السعر (دج)',
  productCommission: 'العمولة (دج)',
  mEmpty: 'لم تُضف أي منتج بعد',
  productAdded: 'تمت إضافة المنتج',
  fillFields: 'يرجى ملء كل الحقول',

  walletTitle: 'المحفظة',
  totalIn: 'الإيرادات',
  totalOut: 'المصروفات',
  transactions: 'المعاملات',
  txEmpty: 'لا توجد معاملات بعد',
  menu: 'القائمة',
  pending: 'قيد الانتظار',
  done: 'مكتمل',

  /* security & session */
  sessionExpired: 'انتهت صلاحية الجلسة، يرجى تسجيل الدخول من جديد',
  sessionActive: 'الجلسة نشطة',
  expiresIn: 'تنتهي خلال',
  attemptsLeft: 'محاولات متبقية: {n}',
  tooManyAttempts: 'محاولات كثيرة، حاول بعد {time}',
  rateLimited: 'تم تجاوز الحد المسموح، أعد المحاولة بعد {time}',
  secured: 'محمي',

  /* validation */
  required: 'هذا الحقل مطلوب',
  invalidEmail: 'بريد إلكتروني غير صالح',
  invalidName: 'الاسم يجب أن يكون بين 3 و40 حرفاً وبأحرف فقط',
  invalidDate: 'تاريخ غير صالح (يوم/شهر/سنة)',
  minAge: 'يجب أن يكون عمرك 18 سنة على الأقل',
  invalidCcp: 'رقم CCP يجب أن يكون من 10 إلى 12 رقماً',
  invalidAmount: 'مبلغ غير صالح',
  aboveMax: 'المبلغ يتجاوز الحد الأقصى المسموح',
  invalidLength: 'طول النص غير مناسب',
  fixErrors: 'يرجى تصحيح الأخطاء المميزة بالأحمر',

  /* legal */
  legal: 'الوثائق القانونية',
  terms: 'الشروط والأحكام',
  privacy: 'سياسة الخصوصية',
  fraud: 'سياسة مكافحة الاحتيال',
  commissions: 'سياسة العمولات',
  readDocs: 'اقرأ الوثائق',
  version: 'الإصدار',
  updated: 'آخر تحديث',
  acceptedOn: 'تمت الموافقة في',
  agreeTermsLink: 'أوافق على الشروط والأحكام وسياسة الخصوصية وسياسة مكافحة الاحتيال',

  /* roles */
  role: 'نوع الحساب',
  roleUser: 'مسوّق',
  roleMerchant: 'تاجر',
  roleAdmin: 'مشرف',
  permissions: 'الصلاحيات',
  adminPanel: 'لوحة التحكم',
  adminAccess: 'دخول المشرف',
  adminPin: 'رمز الدخول',
  adminHint: 'رمز تجريبي: 2468',
  wrongPin: 'رمز دخول خاطئ',
  adminGranted: 'تم تفعيل صلاحيات المشرف',
  adminRevoked: 'تم إلغاء صلاحيات المشرف',
  exitAdmin: 'الخروج من وضع المشرف',
  becomeMerchant: 'تفعيل حساب التاجر',
  merchantRequires: 'يتطلب حساب التاجر توثيق الهوية (KYC) أولاً',
  merchantEnabled: 'تم تفعيل حساب التاجر',

  /* KYC states */
  kycPending: 'قيد المراجعة',
  kycApproved: 'تم التحقق',
  kycRejectedS: 'مرفوض',
  kycReason: 'سبب الرفض',
  resubmit: 'إعادة الإرسال',
  kycAutoNote: 'تتم المراجعة خلال 24 ساعة (مراجع آلي تجريبي في هذه النسخة)',
  kycApprovedMsg: 'تم توثيق هويتك بنجاح، يمكنك السحب الآن',
  kycRejectedMsg: 'تم رفض مستنداتك: {reason}',

  /* withdrawals */
  wdStatusPending: 'قيد المعالجة',
  wdStatusApproved: 'تم الدفع',
  wdStatusRejected: 'مرفوض',
  lockedBalance: 'مبالغ مجمّدة',
  availableForWithdraw: 'متاح للسحب',
  feeLabel: 'رسوم المعالجة',
  netAmount: 'الصافي المستلم',
  wdApprovedMsg: 'تمت الموافقة على سحبك بمبلغ {amount}',
  wdRejectedMsg: 'تم رفض طلب السحب: {reason} — أُعيد المبلغ لرصيدك',
  dailyLimitReached: 'تجاوزت الحد اليومي للسحب',
  wdPolicyNote: 'تُجمّد المبالغ حتى اعتماد الطلب، وتُعاد تلقائياً عند الرفض',

  /* admin */
  adminOverview: 'نظرة عامة',
  queueProofs: 'الإثباتات',
  queueKyc: 'التوثيق',
  queueWithdrawals: 'السحوبات',
  queueCampaigns: 'الحملات',
  auditLog: 'سجل العمليات',
  approve: 'اعتماد',
  reject: 'رفض',
  approved: 'تم الاعتماد',
  rejected: 'تم الرفض',
  rejectReason: 'سبب الرفض',
  reasonRequired: 'يرجى كتابة سبب الرفض',
  noPending: 'لا توجد عناصر قيد المراجعة',
  pendingItems: 'عناصر قيد المراجعة',
  reviewedBy: 'روجع بواسطة',
  autoReviewer: 'المراجع الآلي',
  admin: 'المشرف',
  system: 'النظام',
  totalUsers: 'المستخدمون',
  platformStats: 'إحصائيات المنصة',
  taskManager: 'إدارة المهام',
  enableTask: 'تفعيل',
  disableTask: 'تعطيل',
  taskDisabled: 'تم تعطيل المهمة',
  taskEnabled: 'تم تفعيل المهمة',
  proofApproved: 'تم اعتماد الإثبات وإضافة العمولة',
  proofRejected: 'تم رفض الإثبات: {reason}',
  resubmitProof: 'إعادة إرسال الإثبات',
  attemptsUsed: 'محاولات مستعملة: {n}/{max}',
  noMoreAttempts: 'استنفدت محاولات إعادة الإرسال لهذه المهمة',

  /* campaigns */
  newCampaign: 'حملة جديدة',
  campaignTitle: 'عنوان الحملة',
  campaignDesc: 'وصف مختصر',
  campaignReward: 'العمولة للمسوّق (دج)',
  campaignDifficulty: 'الصعوبة',
  campaignRequirements: 'المتطلبات (سطر لكل شرط)',
  campaignSteps: 'خطوات التنفيذ (سطر لكل خطوة)',
  submitCampaign: 'إرسال للمراجعة',
  campaignSubmitted: 'تم إرسال الحملة لمراجعة المشرف',
  campaignPending: 'قيد المراجعة',
  campaignApproved: 'منشورة',
  campaignRejected: 'مرفوضة',
  myCampaigns: 'حملاتي',
  campaignCost: 'التكلفة الإجمالية',
  platformFee: 'رسوم المنصة',
  noCampaigns: 'لم تنشئ أي حملة بعد',

  /* ledger */
  ledger: 'سجل المعاملات',
  verifyLedger: 'تحقق من السجل',
  ledgerValid: 'السجل سليم ✓ ({n} قيد)',
  ledgerBroken: 'تم كشف تلاعب عند القيد رقم {n}',
  integrity: 'سلامة السجل',
  entrySeq: 'قيد',
  hashLabel: 'البصمة',

  /* commission breakdown */
  baseReward: 'العمولة الأساسية',
  levelBonus: 'مكافأة المستوى',
  totalCredit: 'الإجمالي المضاف',

  /* PWA */
  installApp: 'تثبيت التطبيق',
  installed: 'التطبيق مثبّت',
  installHint: 'ثبّت Zed Earn على شاشتك الرئيسية ليعمل حتى دون إنترنت',
  installDone: 'تم تثبيت التطبيق',
  installUnavailable: 'التثبيت غير متاح في هذا المتصفح',
  offlineMode: 'أنت غير متصل — الوضع دون اتصال',
  updateAvailable: 'تحديث جديد متاح',
  reload: 'تحديث الآن',
  appInfo: 'حول التطبيق',
};

const fr: Dict = {
  appName: 'Zed Earn',
  tagline: 'Gagnez en dinar algérien depuis votre téléphone',
  loading: 'Chargement',

  next: 'Suivant',
  startNow: 'Commencer',
  skip: 'Passer',
  save: 'Enregistrer',
  cancel: 'Annuler',
  back: 'Retour',
  send: 'Envoyer',
  copy: 'Copier',
  share: 'Partager',
  close: 'Fermer',
  confirm: 'Confirmer',
  seeAll: 'Tout voir',
  dzd: 'DZD',
  optional: 'optionnel',

  onb1Title: 'Travaillez depuis votre mobile',
  onb1Desc: 'Réalisez des micro-tâches marketing simples, à tout moment et partout en Algérie. Un téléphone et une connexion suffisent.',
  onb2Title: 'Commissions en dinar algérien',
  onb2Desc: 'Recevez vos commissions en DZD et retirez-les via CCP Algérie Poste ou les portefeuilles électroniques.',
  onb3Title: 'Commencez maintenant',
  onb3Desc: "Créez votre compte en moins d'une minute, complétez votre profil et lancez votre première tâche payée dès aujourd'hui.",

  login: 'Connexion',
  signup: 'Créer un compte',
  authSubLogin: 'Bon retour ! Entrez votre numéro pour continuer',
  authSubSignup: 'Créez votre compte gratuitement et commencez à gagner',
  phone: 'Numéro de téléphone',
  phoneHint: 'Doit commencer par 05, 06 ou 07',
  email: 'E-mail',
  emailOpt: 'E-mail (optionnel)',
  agreeTerms: "J'accepte les conditions d'utilisation et la politique de confidentialité",
  haveAccount: 'Vous avez un compte ? Connectez-vous',
  noAccount: "Pas de compte ? Créez-en un",
  invalidPhone: 'Numéro algérien invalide',
  mustAgree: "Vous devez accepter les conditions",

  otpTitle: 'Vérification du numéro',
  otpSubtitle: 'Entrez le code à 6 chiffres envoyé au',
  otpDemo: 'Code démo',
  otpVerify: 'Vérifier',
  otpResend: 'Renvoyer le code',
  otpResent: 'Nouveau code envoyé',
  otpInvalid: 'Code incorrect, réessayez',

  guideTitle: "Guide de l'utilisateur",
  gIntro: 'Introduction',
  gTasks: 'Tâches',
  gComm: 'Commissions',
  gWd: 'Retrait',
  gRules: 'Règles',
  guideRead: "J'ai lu et compris",

  profileSetup: 'Compléter le profil',
  profileSetupSub: 'Aidez-nous à mieux vous connaître pour accélérer vos retraits',
  uploadAvatar: 'Ajouter une photo',
  fullName: 'Nom complet',
  birthdate: 'Date de naissance',
  wilaya: 'Wilaya',
  ccp: 'Numéro CCP',
  ccpHint: 'Utilisé pour vos retraits',
  profileSaved: 'Profil enregistré',

  home: 'Accueil',
  tasks: 'Tâches',
  withdrawals: 'Retrait',
  account: 'Compte',
  hello: 'Bonjour',
  availableBalance: 'Solde disponible',
  withdraw: 'Retirer',
  deposit: 'Déposer',
  statTasks: 'Tâches',
  statDone: 'Terminées',
  statEarn: 'Commissions',
  availableTasks: 'Tâches disponibles',
  noTasks: 'Aucune tâche disponible',

  easy: 'Facile',
  medium: 'Moyen',
  hard: 'Difficile',
  vip: 'VIP',
  acceptTask: 'Accepter la tâche',
  locked: 'Verrouillé',
  vipLockedMsg: 'Terminez 10 tâches pour débloquer les tâches VIP',
  requirements: 'Prérequis',
  steps: "Étapes d'exécution",
  uploadProof: 'Ajouter la preuve',
  proofHint: "Joignez une capture d'écran prouvant la réalisation",
  sendProof: 'Envoyer la preuve',
  cancelTask: 'Annuler la tâche',
  taskAccepted: 'Tâche acceptée, bonne chance !',
  taskCancelled: 'Tâche annulée',
  proofSent: 'Preuve envoyée pour vérification',
  reviewMsg: 'Nous vérifierons sous 24 heures et la commission sera créditée automatiquement.',
  doneMsg: 'Tâche terminée ! {amount} ont été ajoutés',
  needProof: "Veuillez d'abord joindre une preuve",
  statusAvailable: 'Disponible',
  statusAccepted: 'Acceptée',
  statusReview: 'En vérification',
  statusDone: 'Terminée',
  reward: 'Commission',

  withdrawable: 'Solde retirable',
  minWithdraw: 'Retrait minimum : 1 000 DZD',
  wdMethods: 'Méthodes de retrait',
  mCcp: 'CCP - Algérie Poste',
  mCcpDesc: 'Virement sous 24h',
  mWallet: 'Portefeuilles électroniques',
  mWalletDesc: 'D17 · Mobimoney · BaridiMob',
  mCard: 'Carte bancaire',
  mCardDesc: 'Visa / Mastercard · 3 jours',
  wdHistory: 'Historique des retraits',
  wdEmpty: 'Aucun retrait pour le moment',
  amount: 'Montant',
  requestWithdraw: 'Demander le retrait',
  belowMin: 'Montant inférieur au minimum (1 000 DZD)',
  insufficient: 'Solde insuffisant',
  wdRequested: 'Demande de retrait envoyée',
  kycRequired: 'Vérifiez votre identité (KYC) avant de retirer',
  depositTitle: 'Déposer',
  depositDone: 'Solde démo ajouté',

  profile: 'Profil',
  level: 'Niveau',
  lvlBeginner: 'Débutant',
  lvlActive: 'Actif',
  lvlPro: 'Pro',
  lvlVip: 'VIP',
  nextLevel: 'Progression vers {level}',
  maxLevel: 'Niveau maximum atteint 🎉',
  settings: 'Paramètres',
  kyc: "Vérification d'identité (KYC)",
  referral: 'Parrainage',
  leaderboard: 'Classement',
  wallet: 'Portefeuille & transactions',
  support: 'Support',
  merchant: 'Mode marchand',
  logout: 'Déconnexion',
  loggedOut: 'Déconnecté',
  darkMode: 'Mode sombre',
  language: 'Langue',
  verified: 'Vérifié',
  unverified: 'Non vérifié',

  kycTitle: "Vérification d'identité",
  kycNone: 'Incomplet',
  kycReview: 'En cours de vérification',
  kycVerified: 'Vérifié',
  kycNote: "Vos photos sont protégées et servent uniquement à la vérification.",
  idFront: "Carte d'identité (recto)",
  idBack: "Carte d'identité (verso)",
  selfie: 'Selfie avec la carte',
  kycSubmit: 'Envoyer pour vérification',
  kycMissing: 'Veuillez ajouter les trois photos',
  kycSent: 'Documents envoyés pour vérification',
  tapToUpload: 'Appuyez pour ajouter',

  refTitle: 'Parrainage',
  yourCode: 'Votre code de parrainage',
  refDesc: 'Partagez votre code et gagnez 500 DZD par ami qui rejoint et termine sa première tâche.',
  copied: 'Code copié',
  refCount: 'Filleuls',
  refEarn: 'Gains parrainage',
  refTotal: 'Total',
  shareMsg: 'Rejoins Zed Earn et gagne en dinar algérien ! Mon code : {code}',

  lbTitle: 'Classement',
  lbSub: 'Top 10 des affiliés ce mois-ci',
  tasksCount: 'tâches',

  notifications: 'Notifications',
  notifEmpty: 'Aucune notification',
  markAllRead: 'Tout marquer comme lu',
  markRead: 'Marquer comme lu',
  allRead: 'Toutes les notifications sont lues',

  chatTitle: 'Support',
  chatPlaceholder: 'Écrivez votre message...',
  supportName: 'Équipe Zed Earn',
  chatAuto: "Merci pour votre message ! Notre équipe l'examine et vous répondra sous peu. Pouvez-vous préciser votre problème ?",

  merchantTitle: 'Mode marchand',
  mProducts: 'Mes produits',
  mActive: 'Tâches actives',
  mSales: 'Ventes',
  mRevenue: 'Revenus',
  addProduct: 'Ajouter un produit',
  productName: 'Nom du produit',
  productPrice: 'Prix (DZD)',
  productCommission: 'Commission (DZD)',
  mEmpty: 'Aucun produit ajouté',
  productAdded: 'Produit ajouté',
  fillFields: 'Veuillez remplir tous les champs',

  walletTitle: 'Portefeuille',
  totalIn: 'Entrées',
  totalOut: 'Sorties',
  transactions: 'Transactions',
  txEmpty: 'Aucune transaction',
  menu: 'Menu',
  pending: 'En attente',
  done: 'Terminé',

  /* security & session */
  sessionExpired: 'Session expirée, veuillez vous reconnecter',
  sessionActive: 'Session active',
  expiresIn: 'Expire dans',
  attemptsLeft: 'Tentatives restantes : {n}',
  tooManyAttempts: 'Trop de tentatives, réessayez dans {time}',
  rateLimited: 'Limite atteinte, réessayez dans {time}',
  secured: 'Sécurisé',

  /* validation */
  required: 'Ce champ est obligatoire',
  invalidEmail: 'E-mail invalide',
  invalidName: 'Le nom doit contenir 3 à 40 lettres',
  invalidDate: 'Date invalide (JJ/MM/AAAA)',
  minAge: 'Vous devez avoir au moins 18 ans',
  invalidCcp: 'Le CCP doit contenir 10 à 12 chiffres',
  invalidAmount: 'Montant invalide',
  aboveMax: 'Montant supérieur au plafond autorisé',
  invalidLength: 'Longueur de texte incorrecte',
  fixErrors: 'Veuillez corriger les champs en rouge',

  /* legal */
  legal: 'Documents légaux',
  terms: "Conditions d'utilisation",
  privacy: 'Politique de confidentialité',
  fraud: 'Politique anti-fraude',
  commissions: 'Politique de commissions',
  readDocs: 'Lire les documents',
  version: 'Version',
  updated: 'Mise à jour',
  acceptedOn: 'Accepté le',
  agreeTermsLink: "J'accepte les conditions, la politique de confidentialité et la politique anti-fraude",

  /* roles */
  role: 'Type de compte',
  roleUser: 'Affilié',
  roleMerchant: 'Marchand',
  roleAdmin: 'Administrateur',
  permissions: 'Permissions',
  adminPanel: 'Console admin',
  adminAccess: 'Accès administrateur',
  adminPin: 'Code d’accès',
  adminHint: 'Code démo : 2468',
  wrongPin: 'Code incorrect',
  adminGranted: 'Droits administrateur activés',
  adminRevoked: 'Droits administrateur retirés',
  exitAdmin: 'Quitter le mode admin',
  becomeMerchant: 'Activer le compte marchand',
  merchantRequires: 'Le compte marchand nécessite une vérification KYC',
  merchantEnabled: 'Compte marchand activé',

  /* KYC states */
  kycPending: 'En vérification',
  kycApproved: 'Vérifié',
  kycRejectedS: 'Refusé',
  kycReason: 'Motif du refus',
  resubmit: 'Renvoyer',
  kycAutoNote: 'Vérification sous 24h (relecteur automatique en démo)',
  kycApprovedMsg: 'Identité vérifiée, vous pouvez retirer',
  kycRejectedMsg: 'Documents refusés : {reason}',

  /* withdrawals */
  wdStatusPending: 'En traitement',
  wdStatusApproved: 'Payé',
  wdStatusRejected: 'Refusé',
  lockedBalance: 'Montants gelés',
  availableForWithdraw: 'Disponible au retrait',
  feeLabel: 'Frais de traitement',
  netAmount: 'Net à recevoir',
  wdApprovedMsg: 'Retrait de {amount} approuvé',
  wdRejectedMsg: 'Retrait refusé : {reason} — montant recrédité',
  dailyLimitReached: 'Plafond journalier atteint',
  wdPolicyNote: 'Les montants sont gelés jusqu’à la décision et restitués en cas de refus',

  /* admin */
  adminOverview: 'Vue d’ensemble',
  queueProofs: 'Preuves',
  queueKyc: 'KYC',
  queueWithdrawals: 'Retraits',
  queueCampaigns: 'Campagnes',
  auditLog: 'Journal',
  approve: 'Approuver',
  reject: 'Refuser',
  approved: 'Approuvé',
  rejected: 'Refusé',
  rejectReason: 'Motif du refus',
  reasonRequired: 'Veuillez saisir un motif',
  noPending: 'Aucun élément en attente',
  pendingItems: 'Éléments en attente',
  reviewedBy: 'Revu par',
  autoReviewer: 'Relecteur auto',
  admin: 'Admin',
  system: 'Système',
  totalUsers: 'Utilisateurs',
  platformStats: 'Statistiques plateforme',
  taskManager: 'Gestion des tâches',
  enableTask: 'Activer',
  disableTask: 'Désactiver',
  taskDisabled: 'Tâche désactivée',
  taskEnabled: 'Tâche activée',
  proofApproved: 'Preuve approuvée, commission créditée',
  proofRejected: 'Preuve refusée : {reason}',
  resubmitProof: 'Renvoyer la preuve',
  attemptsUsed: 'Tentatives : {n}/{max}',
  noMoreAttempts: 'Plus de tentatives pour cette tâche',

  /* campaigns */
  newCampaign: 'Nouvelle campagne',
  campaignTitle: 'Titre de la campagne',
  campaignDesc: 'Description courte',
  campaignReward: "Commission de l'affilié (DZD)",
  campaignDifficulty: 'Difficulté',
  campaignRequirements: 'Prérequis (une ligne par item)',
  campaignSteps: 'Étapes (une ligne par étape)',
  submitCampaign: 'Envoyer pour validation',
  campaignSubmitted: 'Campagne envoyée à la modération',
  campaignPending: 'En validation',
  campaignApproved: 'Publiée',
  campaignRejected: 'Refusée',
  myCampaigns: 'Mes campagnes',
  campaignCost: 'Coût total',
  platformFee: 'Frais de plateforme',
  noCampaigns: 'Aucune campagne créée',

  /* ledger */
  ledger: 'Journal des transactions',
  verifyLedger: 'Vérifier le journal',
  ledgerValid: 'Journal intègre ✓ ({n} écritures)',
  ledgerBroken: 'Altération détectée à l’écriture {n}',
  integrity: 'Intégrité',
  entrySeq: 'Écriture',
  hashLabel: 'Empreinte',

  /* commission breakdown */
  baseReward: 'Commission de base',
  levelBonus: 'Bonus de niveau',
  totalCredit: 'Total crédité',

  /* PWA */
  installApp: "Installer l'application",
  installed: 'Application installée',
  installHint: 'Installez Zed Earn sur votre écran d’accueil, même hors ligne',
  installDone: 'Application installée',
  installUnavailable: 'Installation indisponible sur ce navigateur',
  offlineMode: 'Hors ligne — mode déconnecté',
  updateAvailable: 'Mise à jour disponible',
  reload: 'Actualiser',
  appInfo: "À propos",
};

const en: Dict = {
  appName: 'Zed Earn',
  tagline: 'Earn Algerian dinar from your phone',
  loading: 'Loading',

  next: 'Next',
  startNow: 'Get started',
  skip: 'Skip',
  save: 'Save',
  cancel: 'Cancel',
  back: 'Back',
  send: 'Send',
  copy: 'Copy',
  share: 'Share',
  close: 'Close',
  confirm: 'Confirm',
  seeAll: 'See all',
  dzd: 'DZD',
  optional: 'optional',

  onb1Title: 'Work from your phone',
  onb1Desc: 'Complete simple marketing micro-tasks anytime, anywhere in Algeria. All you need is your phone and an internet connection.',
  onb2Title: 'Commissions in Algerian dinar',
  onb2Desc: 'Get paid in DZD and withdraw through CCP Algérie Poste or the local e-wallets you already use.',
  onb3Title: 'Start your journey now',
  onb3Desc: 'Create your account in under a minute, complete your profile and start your first paid task today.',

  login: 'Log in',
  signup: 'Sign up',
  authSubLogin: 'Welcome back! Enter your phone number to continue',
  authSubSignup: 'Create your free account and start earning today',
  phone: 'Phone number',
  phoneHint: 'Must start with 05, 06 or 07',
  email: 'Email',
  emailOpt: 'Email (optional)',
  agreeTerms: 'I agree to the Terms of Service and Privacy Policy',
  haveAccount: 'Already have an account? Log in',
  noAccount: "Don't have an account? Sign up",
  invalidPhone: 'Invalid Algerian phone number',
  mustAgree: 'You must accept the terms first',

  otpTitle: 'Verify your number',
  otpSubtitle: 'Enter the 6-digit code sent to',
  otpDemo: 'Demo code',
  otpVerify: 'Verify',
  otpResend: 'Resend code',
  otpResent: 'A new code has been sent',
  otpInvalid: 'Wrong code, try again',

  guideTitle: 'User guide',
  gIntro: 'Intro',
  gTasks: 'Tasks',
  gComm: 'Commissions',
  gWd: 'Withdrawals',
  gRules: 'Rules',
  guideRead: 'I have read and understood',

  profileSetup: 'Complete your profile',
  profileSetupSub: 'Help us know you better to speed up your withdrawals',
  uploadAvatar: 'Upload photo',
  fullName: 'Full name',
  birthdate: 'Date of birth',
  wilaya: 'Wilaya',
  ccp: 'CCP number',
  ccpHint: 'Used later for withdrawals',
  profileSaved: 'Profile saved',

  home: 'Home',
  tasks: 'Tasks',
  withdrawals: 'Withdraw',
  account: 'Account',
  hello: 'Hello',
  availableBalance: 'Available balance',
  withdraw: 'Withdraw',
  deposit: 'Deposit',
  statTasks: 'Tasks',
  statDone: 'Completed',
  statEarn: 'Earnings',
  availableTasks: 'Available tasks',
  noTasks: 'No tasks available right now',

  easy: 'Easy',
  medium: 'Medium',
  hard: 'Hard',
  vip: 'VIP',
  acceptTask: 'Accept task',
  locked: 'Locked',
  vipLockedMsg: 'Complete 10 tasks to unlock VIP tasks',
  requirements: 'Requirements',
  steps: 'Steps',
  uploadProof: 'Upload proof',
  proofHint: 'Attach a screenshot or photo proving the task is done',
  sendProof: 'Submit proof',
  cancelTask: 'Cancel task',
  taskAccepted: 'Task accepted, good luck!',
  taskCancelled: 'Task cancelled',
  proofSent: 'Proof submitted for review',
  reviewMsg: 'We will review your proof within 24 hours and credit the commission automatically.',
  doneMsg: 'Task complete! {amount} added to your balance',
  needProof: 'Please attach a proof first',
  statusAvailable: 'Available',
  statusAccepted: 'Accepted',
  statusReview: 'In review',
  statusDone: 'Completed',
  reward: 'Commission',

  withdrawable: 'Withdrawable balance',
  minWithdraw: 'Minimum withdrawal: 1,000 DZD',
  wdMethods: 'Withdrawal methods',
  mCcp: 'CCP - Algérie Poste',
  mCcpDesc: 'Transfer within 24 hours',
  mWallet: 'E-wallets',
  mWalletDesc: 'D17 · Mobimoney · BaridiMob',
  mCard: 'Bank card',
  mCardDesc: 'Visa / Mastercard · 3 days',
  wdHistory: 'Withdrawal history',
  wdEmpty: 'No withdrawals yet',
  amount: 'Amount',
  requestWithdraw: 'Request withdrawal',
  belowMin: 'Amount below the minimum (1,000 DZD)',
  insufficient: 'Insufficient balance',
  wdRequested: 'Withdrawal request sent',
  kycRequired: 'You must verify your identity (KYC) before withdrawing',
  depositTitle: 'Deposit',
  depositDone: 'Demo balance added',

  profile: 'Profile',
  level: 'Level',
  lvlBeginner: 'Beginner',
  lvlActive: 'Active',
  lvlPro: 'Pro',
  lvlVip: 'VIP',
  nextLevel: 'Progress to {level}',
  maxLevel: 'Max level reached 🎉',
  settings: 'Settings',
  kyc: 'Identity verification (KYC)',
  referral: 'Referrals',
  leaderboard: 'Leaderboard',
  wallet: 'Wallet & transactions',
  support: 'Support',
  merchant: 'Merchant mode',
  logout: 'Log out',
  loggedOut: 'Logged out',
  darkMode: 'Dark mode',
  language: 'Language',
  verified: 'Verified',
  unverified: 'Unverified',

  kycTitle: 'Identity verification',
  kycNone: 'Incomplete',
  kycReview: 'Under review',
  kycVerified: 'Verified',
  kycNote: 'Your photos are protected and used only to verify your identity.',
  idFront: 'ID card (front)',
  idBack: 'ID card (back)',
  selfie: 'Selfie with ID',
  kycSubmit: 'Submit for verification',
  kycMissing: 'Please upload all three photos',
  kycSent: 'Documents submitted for review',
  tapToUpload: 'Tap to upload',

  refTitle: 'Referrals',
  yourCode: 'Your referral code',
  refDesc: 'Share your code and earn 500 DZD for every friend who joins and completes their first task.',
  copied: 'Code copied',
  refCount: 'Referrals',
  refEarn: 'Referral earnings',
  refTotal: 'Total',
  shareMsg: 'Join Zed Earn and earn in Algerian dinar! Use my code: {code}',

  lbTitle: 'Leaderboard',
  lbSub: 'Top 10 affiliates this month',
  tasksCount: 'tasks',

  notifications: 'Notifications',
  notifEmpty: 'No notifications',
  markAllRead: 'Mark all as read',
  markRead: 'Mark as read',
  allRead: 'All notifications marked as read',

  chatTitle: 'Support chat',
  chatPlaceholder: 'Type your message...',
  supportName: 'Zed Earn team',
  chatAuto: 'Thanks for reaching out! Our team is reviewing your message and will reply shortly. Could you share more details?',

  merchantTitle: 'Merchant mode',
  mProducts: 'My products',
  mActive: 'Active tasks',
  mSales: 'Sales',
  mRevenue: 'Revenue',
  addProduct: 'Add new product',
  productName: 'Product name',
  productPrice: 'Price (DZD)',
  productCommission: 'Commission (DZD)',
  mEmpty: 'No products added yet',
  productAdded: 'Product added',
  fillFields: 'Please fill in all fields',

  walletTitle: 'Wallet',
  totalIn: 'Income',
  totalOut: 'Expenses',
  transactions: 'Transactions',
  txEmpty: 'No transactions yet',
  menu: 'Menu',
  pending: 'Pending',
  done: 'Completed',

  /* security & session */
  sessionExpired: 'Your session expired, please log in again',
  sessionActive: 'Session active',
  expiresIn: 'Expires in',
  attemptsLeft: 'Attempts left: {n}',
  tooManyAttempts: 'Too many attempts, try again in {time}',
  rateLimited: 'Rate limit reached, retry in {time}',
  secured: 'Secured',

  /* validation */
  required: 'This field is required',
  invalidEmail: 'Invalid email address',
  invalidName: 'Name must be 3–40 letters',
  invalidDate: 'Invalid date (DD/MM/YYYY)',
  minAge: 'You must be at least 18 years old',
  invalidCcp: 'CCP must be 10 to 12 digits',
  invalidAmount: 'Invalid amount',
  aboveMax: 'Amount exceeds the allowed cap',
  invalidLength: 'Text length is not valid',
  fixErrors: 'Please fix the highlighted fields',

  /* legal */
  legal: 'Legal documents',
  terms: 'Terms of Service',
  privacy: 'Privacy Policy',
  fraud: 'Anti-Fraud Policy',
  commissions: 'Commission Policy',
  readDocs: 'Read the documents',
  version: 'Version',
  updated: 'Updated',
  acceptedOn: 'Accepted on',
  agreeTermsLink: 'I agree to the Terms, Privacy Policy and Anti-Fraud Policy',

  /* roles */
  role: 'Account type',
  roleUser: 'Affiliate',
  roleMerchant: 'Merchant',
  roleAdmin: 'Administrator',
  permissions: 'Permissions',
  adminPanel: 'Admin console',
  adminAccess: 'Administrator access',
  adminPin: 'Access code',
  adminHint: 'Demo code: 2468',
  wrongPin: 'Wrong access code',
  adminGranted: 'Administrator rights granted',
  adminRevoked: 'Administrator rights revoked',
  exitAdmin: 'Exit admin mode',
  becomeMerchant: 'Enable merchant account',
  merchantRequires: 'Merchant accounts require KYC verification first',
  merchantEnabled: 'Merchant account enabled',

  /* KYC states */
  kycPending: 'Under review',
  kycApproved: 'Verified',
  kycRejectedS: 'Rejected',
  kycReason: 'Rejection reason',
  resubmit: 'Resubmit',
  kycAutoNote: 'Reviewed within 24h (automated reviewer in this demo)',
  kycApprovedMsg: 'Identity verified — you can withdraw now',
  kycRejectedMsg: 'Documents rejected: {reason}',

  /* withdrawals */
  wdStatusPending: 'Processing',
  wdStatusApproved: 'Paid',
  wdStatusRejected: 'Rejected',
  lockedBalance: 'Locked funds',
  availableForWithdraw: 'Available to withdraw',
  feeLabel: 'Processing fee',
  netAmount: 'Net payout',
  wdApprovedMsg: 'Withdrawal of {amount} approved',
  wdRejectedMsg: 'Withdrawal rejected: {reason} — funds returned',
  dailyLimitReached: 'Daily withdrawal cap reached',
  wdPolicyNote: 'Funds are locked until a decision and refunded on rejection',

  /* admin */
  adminOverview: 'Overview',
  queueProofs: 'Proofs',
  queueKyc: 'KYC',
  queueWithdrawals: 'Withdrawals',
  queueCampaigns: 'Campaigns',
  auditLog: 'Audit log',
  approve: 'Approve',
  reject: 'Reject',
  approved: 'Approved',
  rejected: 'Rejected',
  rejectReason: 'Rejection reason',
  reasonRequired: 'Please provide a reason',
  noPending: 'Nothing pending review',
  pendingItems: 'Pending items',
  reviewedBy: 'Reviewed by',
  autoReviewer: 'Auto reviewer',
  admin: 'Admin',
  system: 'System',
  totalUsers: 'Users',
  platformStats: 'Platform stats',
  taskManager: 'Task manager',
  enableTask: 'Enable',
  disableTask: 'Disable',
  taskDisabled: 'Task disabled',
  taskEnabled: 'Task enabled',
  proofApproved: 'Proof approved, commission credited',
  proofRejected: 'Proof rejected: {reason}',
  resubmitProof: 'Resubmit proof',
  attemptsUsed: 'Attempts: {n}/{max}',
  noMoreAttempts: 'No resubmission attempts left for this task',

  /* campaigns */
  newCampaign: 'New campaign',
  campaignTitle: 'Campaign title',
  campaignDesc: 'Short description',
  campaignReward: 'Affiliate commission (DZD)',
  campaignDifficulty: 'Difficulty',
  campaignRequirements: 'Requirements (one per line)',
  campaignSteps: 'Steps (one per line)',
  submitCampaign: 'Submit for review',
  campaignSubmitted: 'Campaign submitted for moderation',
  campaignPending: 'In review',
  campaignApproved: 'Published',
  campaignRejected: 'Rejected',
  myCampaigns: 'My campaigns',
  campaignCost: 'Total cost',
  platformFee: 'Platform fee',
  noCampaigns: 'No campaigns created yet',

  /* ledger */
  ledger: 'Transaction ledger',
  verifyLedger: 'Verify ledger',
  ledgerValid: 'Ledger intact ✓ ({n} entries)',
  ledgerBroken: 'Tampering detected at entry {n}',
  integrity: 'Integrity',
  entrySeq: 'Entry',
  hashLabel: 'Hash',

  /* commission breakdown */
  baseReward: 'Base commission',
  levelBonus: 'Level bonus',
  totalCredit: 'Total credited',

  /* PWA */
  installApp: 'Install app',
  installed: 'App installed',
  installHint: 'Install Zed Earn to your home screen — works offline too',
  installDone: 'App installed',
  installUnavailable: 'Installation is not available in this browser',
  offlineMode: 'You are offline — offline mode',
  updateAvailable: 'A new update is available',
  reload: 'Reload now',
  appInfo: 'About',
};

export const TRANSLATIONS: Record<Lang, Dict> = { ar, fr, en };

/* ── Guide content ─────────────────────────────────── */
export type GuideSection = { id: string; titleKey: string; body: Record<Lang, string[]> };

export const GUIDE: GuideSection[] = [
  {
    id: 'intro',
    titleKey: 'gIntro',
    body: {
      ar: [
        'Zed Earn منصة تسويق بالعمولة جزائرية 100%، تربط بين التجار المحليين والمسوّقين الذين ينجزون مهام تسويقية بسيطة مقابل عمولة بالدينار الجزائري.',
        'كل ما تحتاجه هو هاتف ذكي، حساب موثّق، ورغبة في العمل يومياً لبضع دقائق. لا رسوم اشتراك ولا مبالغ مسبقة إطلاقاً.',
        'التطبيق يعمل بثلاث لغات: العربية، الفرنسية والإنجليزية، ويمكنك تغيير اللغة والوضع الليلي في أي وقت من الإعدادات.',
      ],
      fr: [
        "Zed Earn est une plateforme d'affiliation 100% algérienne qui relie les marchands locaux aux affiliés réalisant des tâches marketing simples contre une commission en dinar.",
        "Il vous suffit d'un smartphone, d'un compte vérifié et de quelques minutes par jour. Aucun frais d'inscription, jamais.",
        "L'application est disponible en arabe, français et anglais. Vous pouvez changer de langue ou activer le mode sombre à tout moment.",
      ],
      en: [
        'Zed Earn is a 100% Algerian affiliate marketing platform connecting local merchants with affiliates who complete simple marketing tasks for a commission in dinar.',
        'All you need is a smartphone, a verified account and a few minutes a day. No subscription fees, ever.',
        'The app supports Arabic, French and English. You can switch language or dark mode at any time from settings.',
      ],
    },
  },
  {
    id: 'tasks',
    titleKey: 'gTasks',
    body: {
      ar: [
        'المهام مقسمة إلى 4 مستويات: سهل، متوسط، صعب، و VIP. كل مهمة تعرض العمولة، المتطلبات وخطوات التنفيذ قبل قبولها.',
        'بعد قبول المهمة يكون لديك 24 ساعة لإرسال الإثبات (لقطة شاشة أو صورة). يمكنك إلغاء المهمة في أي وقت قبل الإرسال.',
        'مهام VIP تُفتح تلقائياً بعد إكمال 10 مهام بنجاح، وعمولاتها أعلى بكثير.',
      ],
      fr: [
        'Les tâches se divisent en 4 niveaux : facile, moyen, difficile et VIP. Chaque tâche affiche sa commission, ses prérequis et ses étapes avant acceptation.',
        "Après acceptation, vous avez 24 heures pour envoyer la preuve (capture d'écran ou photo). Vous pouvez annuler avant l'envoi.",
        'Les tâches VIP se débloquent après 10 tâches réussies et offrent des commissions bien plus élevées.',
      ],
      en: [
        'Tasks come in 4 tiers: easy, medium, hard and VIP. Every task shows its commission, requirements and steps before you accept it.',
        'Once accepted you have 24 hours to submit proof (screenshot or photo). You can cancel any time before submitting.',
        'VIP tasks unlock automatically after 10 successfully completed tasks and pay significantly more.',
      ],
    },
  },
  {
    id: 'commissions',
    titleKey: 'gComm',
    body: {
      ar: [
        'تُحسب كل العمولات بالدينار الجزائري (DZD) وتُضاف إلى رصيدك مباشرة بعد قبول الإثبات من طرف فريق المراجعة.',
        'المراجعة تستغرق عادة أقل من 24 ساعة. إذا رُفض الإثبات ستصلك رسالة توضح السبب مع إمكانية إعادة الإرسال.',
        'تحصل أيضاً على 500 دج عن كل صديق تدعوه بكود الإحالة الخاص بك بعد إكماله لأول مهمة.',
      ],
      fr: [
        'Toutes les commissions sont calculées en dinar algérien (DZD) et créditées dès validation de votre preuve par notre équipe.',
        "La vérification prend généralement moins de 24 heures. En cas de refus, vous recevez le motif et pouvez renvoyer la preuve.",
        'Vous gagnez aussi 500 DZD par ami invité avec votre code de parrainage dès sa première tâche validée.',
      ],
      en: [
        'All commissions are calculated in Algerian dinar (DZD) and credited as soon as our review team validates your proof.',
        'Reviews usually take less than 24 hours. If a proof is rejected you get the reason and can resubmit.',
        'You also earn 500 DZD for every friend invited with your referral code once they complete their first task.',
      ],
    },
  },
  {
    id: 'withdraw',
    titleKey: 'gWd',
    body: {
      ar: [
        'الحد الأدنى للسحب هو 1,000 دج. يجب توثيق هويتك (KYC) مرة واحدة فقط قبل أول عملية سحب.',
        'الطرق المتاحة: CCP بريد الجزائر (خلال 24 ساعة)، المحافظ الإلكترونية D17 و Mobimoney و BaridiMob، أو البطاقة البنكية (3 أيام).',
        'تأكد من صحة رقم CCP في ملفك الشخصي، فالتحويل الخاطئ لا يمكن استرجاعه.',
      ],
      fr: [
        "Le retrait minimum est de 1 000 DZD. La vérification d'identité (KYC) est requise une seule fois avant le premier retrait.",
        'Méthodes : CCP Algérie Poste (sous 24h), portefeuilles D17, Mobimoney, BaridiMob, ou carte bancaire (3 jours).',
        'Vérifiez bien votre numéro CCP : un virement erroné est irrécupérable.',
      ],
      en: [
        'Minimum withdrawal is 1,000 DZD. Identity verification (KYC) is required once before your first withdrawal.',
        'Methods: CCP Algérie Poste (within 24h), D17 / Mobimoney / BaridiMob wallets, or bank card (3 days).',
        'Double-check your CCP number in your profile — a wrong transfer cannot be reversed.',
      ],
    },
  },
  {
    id: 'rules',
    titleKey: 'gRules',
    body: {
      ar: [
        'حساب واحد لكل شخص. الحسابات المكررة أو المزيفة يتم حظرها نهائياً مع فقدان الرصيد.',
        'ممنوع استعمال البوتات أو الإثباتات المعدّلة أو النقرات الوهمية. المراجعة تتم يدوياً وآلياً.',
        'احترم شروط كل مهمة والعلامات التجارية المشاركة. الاحتيال يؤدي لإلغاء العمولات المكتسبة.',
        'خدمة الدعم متاحة من داخل التطبيق 7/7 عبر تبويب الدعم الفني.',
      ],
      fr: [
        'Un seul compte par personne. Les comptes multiples ou faux sont bannis définitivement avec perte du solde.',
        'Bots, preuves modifiées et faux clics sont interdits. La vérification est manuelle et automatique.',
        'Respectez les conditions de chaque tâche et les marques partenaires. Toute fraude annule les commissions.',
        'Le support est disponible 7j/7 depuis le chat intégré.',
      ],
      en: [
        'One account per person. Duplicate or fake accounts are permanently banned and lose their balance.',
        'Bots, edited proofs and fake clicks are forbidden. Reviews are both manual and automated.',
        'Respect each task’s conditions and partner brands. Fraud voids all earned commissions.',
        'Support is available 7/7 from the in-app chat.',
      ],
    },
  },
];

/* ── Wilayas ───────────────────────────────────────── */
export const WILAYAS: Record<Lang, string[]> = {
  ar: ['الجزائر', 'وهران', 'قسنطينة', 'عنابة', 'سطيف', 'باتنة', 'بجاية', 'تلمسان', 'بليدة', 'ورقلة', 'تيزي وزو', 'أخرى'],
  fr: ['Alger', 'Oran', 'Constantine', 'Annaba', 'Sétif', 'Batna', 'Béjaïa', 'Tlemcen', 'Blida', 'Ouargla', 'Tizi Ouzou', 'Autre'],
  en: ['Algiers', 'Oran', 'Constantine', 'Annaba', 'Setif', 'Batna', 'Bejaia', 'Tlemcen', 'Blida', 'Ouargla', 'Tizi Ouzou', 'Other'],
};

/* ── Tasks ─────────────────────────────────────────── */
export type Difficulty = 'easy' | 'medium' | 'hard' | 'vip';
export type TaskDef = {
  id: string;
  icon: string;
  color: string;
  difficulty: Difficulty;
  reward: number;
  title: Record<Lang, string>;
  desc: Record<Lang, string>;
  requirements: Record<Lang, string[]>;
  steps: Record<Lang, string[]>;
};

export const TASKS: TaskDef[] = [
  {
    id: 't1',
    icon: 'logo-instagram',
    color: '#E1306C',
    difficulty: 'easy',
    reward: 250,
    title: { ar: 'متابعة صفحة انستغرام', fr: 'Suivre une page Instagram', en: 'Follow an Instagram page' },
    desc: { ar: 'تابع صفحة متجر شريك وتفاعل مع 3 منشورات', fr: 'Suivez une boutique partenaire et likez 3 posts', en: 'Follow a partner store and like 3 posts' },
    requirements: {
      ar: ['حساب انستغرام حقيقي عمره أكثر من شهر', 'لا يقل عدد المتابعين عن 50', 'إبقاء المتابعة لمدة 30 يوم'],
      fr: ['Compte Instagram réel de plus d’un mois', 'Au moins 50 abonnés', 'Rester abonné 30 jours'],
      en: ['Real Instagram account older than one month', 'At least 50 followers', 'Stay subscribed for 30 days'],
    },
    steps: {
      ar: ['افتح رابط الصفحة @zedstore_dz', 'اضغط زر متابعة', 'أعجب بآخر 3 منشورات', 'التقط لقطة شاشة تظهر المتابعة'],
      fr: ['Ouvrez la page @zedstore_dz', 'Cliquez sur Suivre', 'Aimez les 3 derniers posts', 'Prenez une capture d’écran'],
      en: ['Open the page @zedstore_dz', 'Tap Follow', 'Like the latest 3 posts', 'Take a screenshot as proof'],
    },
  },
  {
    id: 't2',
    icon: 'share-social',
    color: '#2563EB',
    difficulty: 'easy',
    reward: 300,
    title: { ar: 'مشاركة منشور ترويجي', fr: 'Partager une publication', en: 'Share a promo post' },
    desc: { ar: 'شارك منشور العرض على فيسبوك أو ستوري', fr: 'Partagez l’offre sur Facebook ou en story', en: 'Share the offer on Facebook or your story' },
    requirements: {
      ar: ['حساب فيسبوك نشط', 'المنشور عام وليس خاص', 'إبقاؤه 7 أيام على الأقل'],
      fr: ['Compte Facebook actif', 'Publication publique', 'Garder 7 jours minimum'],
      en: ['Active Facebook account', 'Post must be public', 'Keep it at least 7 days'],
    },
    steps: {
      ar: ['انسخ رابط العرض من التطبيق', 'انشره على حسابك مع الوسم #ZedEarn', 'اضبط الخصوصية على عام', 'أرسل لقطة شاشة'],
      fr: ['Copiez le lien de l’offre', 'Publiez-le avec #ZedEarn', 'Mettez la visibilité en public', 'Envoyez une capture'],
      en: ['Copy the offer link from the app', 'Post it with #ZedEarn', 'Set visibility to public', 'Submit a screenshot'],
    },
  },
  {
    id: 't3',
    icon: 'download',
    color: '#10B981',
    difficulty: 'easy',
    reward: 400,
    title: { ar: 'تحميل تطبيق شريك', fr: 'Installer une app partenaire', en: 'Install a partner app' },
    desc: { ar: 'حمّل التطبيق وافتحه لمدة دقيقتين', fr: 'Installez l’app et utilisez-la 2 minutes', en: 'Install the app and use it for 2 minutes' },
    requirements: {
      ar: ['هاتف أندرويد أو iOS', 'عدم حذف التطبيق قبل 48 ساعة', 'إنشاء حساب داخل التطبيق'],
      fr: ['Téléphone Android ou iOS', 'Ne pas désinstaller avant 48h', 'Créer un compte dans l’app'],
      en: ['Android or iOS phone', 'Do not uninstall before 48h', 'Create an account inside the app'],
    },
    steps: {
      ar: ['اضغط رابط التحميل', 'ثبّت التطبيق', 'أنشئ حساباً جديداً', 'صوّر شاشة الحساب الجديد'],
      fr: ['Cliquez sur le lien', 'Installez l’application', 'Créez un compte', 'Capturez l’écran du compte'],
      en: ['Tap the download link', 'Install the app', 'Create a new account', 'Screenshot the account screen'],
    },
  },
  {
    id: 't4',
    icon: 'star',
    color: '#F59E0B',
    difficulty: 'medium',
    reward: 700,
    title: { ar: 'كتابة تقييم للمتجر', fr: 'Rédiger un avis boutique', en: 'Write a store review' },
    desc: { ar: 'اكتب تقييماً صادقاً من 40 كلمة على الأقل', fr: 'Rédigez un avis honnête de 40 mots minimum', en: 'Write an honest review of at least 40 words' },
    requirements: {
      ar: ['تقييم أصلي غير منسوخ', '40 كلمة على الأقل', 'بدون ألفاظ غير لائقة'],
      fr: ['Avis original non copié', '40 mots minimum', 'Sans propos inappropriés'],
      en: ['Original, non-copied review', 'At least 40 words', 'No inappropriate language'],
    },
    steps: {
      ar: ['افتح صفحة المتجر على Google Maps', 'اضغط على كتابة تقييم', 'اكتب تجربتك بصدق', 'أرسل لقطة شاشة للتقييم المنشور'],
      fr: ['Ouvrez la fiche Google Maps', 'Cliquez sur Rédiger un avis', 'Décrivez votre expérience', 'Envoyez la capture de l’avis publié'],
      en: ['Open the store on Google Maps', 'Tap Write a review', 'Describe your experience', 'Submit a screenshot of the published review'],
    },
  },
  {
    id: 't5',
    icon: 'videocam',
    color: '#EF4444',
    difficulty: 'medium',
    reward: 1200,
    title: { ar: 'فيديو تيك توك قصير', fr: 'Vidéo TikTok courte', en: 'Short TikTok video' },
    desc: { ar: 'صوّر فيديو 15 ثانية يعرض المنتج', fr: 'Filmez 15 secondes présentant le produit', en: 'Record a 15-second product video' },
    requirements: {
      ar: ['حساب تيك توك عام', 'الفيديو بجودة جيدة', 'ذكر اسم العلامة في الوصف'],
      fr: ['Compte TikTok public', 'Bonne qualité vidéo', 'Mentionner la marque'],
      en: ['Public TikTok account', 'Good video quality', 'Mention the brand in the caption'],
    },
    steps: {
      ar: ['صوّر فيديو 15 ثانية', 'أضف الوسم #ZedEarn', 'انشره على حسابك', 'أرسل رابط ولقطة الفيديو'],
      fr: ['Filmez 15 secondes', 'Ajoutez #ZedEarn', 'Publiez la vidéo', 'Envoyez le lien et la capture'],
      en: ['Record a 15s video', 'Add #ZedEarn hashtag', 'Publish it', 'Submit the link and screenshot'],
    },
  },
  {
    id: 't6',
    icon: 'people',
    color: '#7C3AED',
    difficulty: 'medium',
    reward: 900,
    title: { ar: 'دعوة 5 أصدقاء لمجموعة', fr: 'Inviter 5 amis dans un groupe', en: 'Invite 5 friends to a group' },
    desc: { ar: 'أضف 5 أصدقاء حقيقيين لمجموعة العروض', fr: 'Ajoutez 5 amis réels au groupe offres', en: 'Add 5 real friends to the deals group' },
    requirements: {
      ar: ['أصدقاء حقيقيون من الجزائر', 'بقاؤهم في المجموعة 7 أيام', 'بدون حسابات وهمية'],
      fr: ['Amis réels résidant en Algérie', 'Rester 7 jours dans le groupe', 'Pas de faux comptes'],
      en: ['Real friends based in Algeria', 'They stay 7 days in the group', 'No fake accounts'],
    },
    steps: {
      ar: ['افتح رابط المجموعة', 'أضف 5 أصدقاء', 'تأكد من قبولهم', 'أرسل لقطة قائمة الأعضاء'],
      fr: ['Ouvrez le lien du groupe', 'Ajoutez 5 amis', 'Vérifiez leur adhésion', 'Envoyez la capture des membres'],
      en: ['Open the group link', 'Add 5 friends', 'Make sure they joined', 'Submit the members screenshot'],
    },
  },
  {
    id: 't7',
    icon: 'cart',
    color: '#0EA5E9',
    difficulty: 'hard',
    reward: 2500,
    title: { ar: 'بيع منتج بالعمولة', fr: 'Vendre un produit affilié', en: 'Sell an affiliate product' },
    desc: { ar: 'حقق أول عملية بيع عبر رابطك الخاص', fr: 'Réalisez une première vente via votre lien', en: 'Make your first sale through your link' },
    requirements: {
      ar: ['استعمال رابط الإحالة الخاص بك', 'الطلب مؤكد وغير ملغى', 'التسليم داخل الجزائر'],
      fr: ['Utiliser votre lien d’affiliation', 'Commande confirmée non annulée', 'Livraison en Algérie'],
      en: ['Use your own affiliate link', 'Order confirmed and not cancelled', 'Delivery inside Algeria'],
    },
    steps: {
      ar: ['انسخ رابط المنتج من التطبيق', 'روّج له عبر شبكاتك', 'انتظر تأكيد الطلب', 'أرسل لقطة تأكيد الطلب'],
      fr: ['Copiez le lien produit', 'Faites-en la promotion', 'Attendez la confirmation', 'Envoyez la capture de commande'],
      en: ['Copy the product link', 'Promote it on your networks', 'Wait for order confirmation', 'Submit the order screenshot'],
    },
  },
  {
    id: 't8',
    icon: 'megaphone',
    color: '#F97316',
    difficulty: 'hard',
    reward: 3000,
    title: { ar: 'حملة إعلانية صغيرة', fr: 'Mini campagne publicitaire', en: 'Small ad campaign' },
    desc: { ar: 'أطلق حملة على صفحتك تحقق 1000 مشاهدة', fr: 'Lancez une campagne atteignant 1000 vues', en: 'Run a campaign reaching 1,000 views' },
    requirements: {
      ar: ['صفحة يتابعها 500 شخص على الأقل', '1000 مشاهدة حقيقية', 'مدة الحملة 3 أيام'],
      fr: ['Page d’au moins 500 abonnés', '1000 vues réelles', 'Campagne de 3 jours'],
      en: ['Page with at least 500 followers', '1,000 real views', '3-day campaign'],
    },
    steps: {
      ar: ['جهّز المحتوى الإعلاني', 'انشره على صفحتك', 'تابع الإحصائيات 3 أيام', 'أرسل لقطة الإحصائيات'],
      fr: ['Préparez le visuel', 'Publiez sur votre page', 'Suivez les stats 3 jours', 'Envoyez la capture des stats'],
      en: ['Prepare the ad content', 'Publish it on your page', 'Track stats for 3 days', 'Submit the stats screenshot'],
    },
  },
  {
    id: 't9',
    icon: 'diamond',
    color: '#8B5CF6',
    difficulty: 'vip',
    reward: 6000,
    title: { ar: 'سفير العلامة التجارية', fr: 'Ambassadeur de marque', en: 'Brand ambassador' },
    desc: { ar: 'تعاون شهري مع علامة جزائرية معروفة', fr: 'Collaboration mensuelle avec une marque', en: 'Monthly collaboration with a known brand' },
    requirements: {
      ar: ['إكمال 10 مهام على الأقل', 'حساب موثّق KYC', 'محتوى أسبوعي لمدة شهر'],
      fr: ['10 tâches minimum complétées', 'Compte vérifié KYC', 'Contenu hebdomadaire pendant un mois'],
      en: ['At least 10 completed tasks', 'KYC verified account', 'Weekly content for one month'],
    },
    steps: {
      ar: ['قدّم ملفك للعلامة', 'انتظر الموافقة', 'انشر 4 محتويات', 'أرسل تقرير الحملة'],
      fr: ['Envoyez votre dossier', 'Attendez la validation', 'Publiez 4 contenus', 'Envoyez le rapport'],
      en: ['Submit your profile to the brand', 'Wait for approval', 'Publish 4 pieces of content', 'Submit the campaign report'],
    },
  },
  {
    id: 't10',
    icon: 'trophy',
    color: '#D97706',
    difficulty: 'vip',
    reward: 10000,
    title: { ar: 'تحدي 20 مبيعة', fr: 'Défi 20 ventes', en: '20 sales challenge' },
    desc: { ar: 'حقق 20 عملية بيع خلال 30 يوماً', fr: 'Réalisez 20 ventes en 30 jours', en: 'Make 20 sales within 30 days' },
    requirements: {
      ar: ['إكمال 10 مهام على الأقل', '20 طلب مؤكد', 'نسبة إلغاء أقل من 10%'],
      fr: ['10 tâches minimum complétées', '20 commandes confirmées', 'Moins de 10% d’annulation'],
      en: ['At least 10 completed tasks', '20 confirmed orders', 'Cancellation rate under 10%'],
    },
    steps: {
      ar: ['فعّل روابطك الخاصة', 'روّج يومياً', 'تابع لوحة المبيعات', 'أرسل تقرير المبيعات النهائي'],
      fr: ['Activez vos liens', 'Faites la promo chaque jour', 'Suivez le tableau des ventes', 'Envoyez le rapport final'],
      en: ['Activate your links', 'Promote daily', 'Track the sales dashboard', 'Submit the final sales report'],
    },
  },
];

/* ── Leaderboard ───────────────────────────────────── */
export const LEADERBOARD = [
  { name: 'Yacine B.', tasks: 148, earnings: 187500 },
  { name: 'Amina K.', tasks: 132, earnings: 164200 },
  { name: 'Sofiane M.', tasks: 121, earnings: 151800 },
  { name: 'Nadia H.', tasks: 109, earnings: 133400 },
  { name: 'Karim D.', tasks: 97, earnings: 119900 },
  { name: 'Lina T.', tasks: 88, earnings: 104300 },
  { name: 'Bilal Z.', tasks: 76, earnings: 92100 },
  { name: 'Sara A.', tasks: 65, earnings: 80500 },
  { name: 'Riad N.', tasks: 54, earnings: 67200 },
  { name: 'Meriem O.', tasks: 47, earnings: 58900 },
];

/* ── Demo notifications ────────────────────────────── */
export type NotifType = 'success' | 'warning' | 'info';
export const DEMO_NOTIFICATIONS: {
  id: string; type: NotifType; title: Record<Lang, string>; body: Record<Lang, string>; time: Record<Lang, string>; read: boolean;
}[] = [
  {
    id: 'n1',
    type: 'success',
    title: { ar: 'مرحباً بك في Zed Earn', fr: 'Bienvenue sur Zed Earn', en: 'Welcome to Zed Earn' },
    body: { ar: 'حسابك جاهز! أكمل ملفك الشخصي لفتح كل المهام.', fr: 'Votre compte est prêt ! Complétez votre profil.', en: 'Your account is ready! Complete your profile to unlock all tasks.' },
    time: { ar: 'الآن', fr: 'maintenant', en: 'now' },
    read: false,
  },
  {
    id: 'n2',
    type: 'info',
    title: { ar: 'مهام جديدة متاحة', fr: 'Nouvelles tâches disponibles', en: 'New tasks available' },
    body: { ar: 'تمت إضافة 4 مهام جديدة بعمولات تصل إلى 3,000 دج.', fr: '4 nouvelles tâches jusqu’à 3 000 DZD.', en: '4 new tasks added with commissions up to 3,000 DZD.' },
    time: { ar: 'منذ ساعتين', fr: 'il y a 2 h', en: '2h ago' },
    read: false,
  },
  {
    id: 'n3',
    type: 'warning',
    title: { ar: 'وثّق هويتك', fr: 'Vérifiez votre identité', en: 'Verify your identity' },
    body: { ar: 'التحقق من الهوية مطلوب قبل أول عملية سحب.', fr: 'Le KYC est requis avant le premier retrait.', en: 'KYC is required before your first withdrawal.' },
    time: { ar: 'أمس', fr: 'hier', en: 'yesterday' },
    read: true,
  },
];

export const DEMO_CHAT: { id: string; from: 'support' | 'user'; text: Record<Lang, string>; time: string }[] = [
  {
    id: 'c1',
    from: 'support',
    text: {
      ar: 'أهلاً بك في دعم Zed Earn 👋 كيف يمكننا مساعدتك اليوم؟',
      fr: 'Bienvenue au support Zed Earn 👋 Comment pouvons-nous vous aider ?',
      en: 'Welcome to Zed Earn support 👋 How can we help you today?',
    },
    time: '09:12',
  },
];

export const SUPPORT_REPLIES: Record<Lang, string[]> = {
  ar: [
    'شكراً على تواصلك! سنراجع طلبك ونعود إليك خلال دقائق.',
    'يمكنك متابعة حالة مهامك من تبويب المهام في أي وقت.',
    'عمليات السحب عبر CCP تصل عادة خلال 24 ساعة عمل.',
    'هل جربت إكمال ملفك الشخصي؟ هذا يفتح مهاماً أعلى عمولة.',
  ],
  fr: [
    'Merci pour votre message ! Nous revenons vers vous dans quelques minutes.',
    'Vous pouvez suivre vos tâches depuis l’onglet Tâches à tout moment.',
    'Les retraits CCP arrivent généralement sous 24 heures ouvrables.',
    'Avez-vous complété votre profil ? Cela débloque des tâches mieux payées.',
  ],
  en: [
    'Thanks for reaching out! We will get back to you within minutes.',
    'You can track your tasks any time from the Tasks tab.',
    'CCP withdrawals usually arrive within 24 working hours.',
    'Have you completed your profile? It unlocks higher paying tasks.',
  ],
};
